<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>HatTrick.Text.TestHarness</AssemblyTitle>
    <Product>HatTrick.Text.TestHarness</Product>
    <Copyright>Copyright ©  2018</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <LangVersion>7.2</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\HatTrick.Text.Templating\HatTrick.Text.Templating.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="HatTrick.Reflection" Version="3.0.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.6.0-preview3.19128.7" />
  </ItemGroup>
</Project>